CREATE TABLE IF NOT EXISTS livrosAdd commentMore actions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ano_publicacao integer,
    autor varchar(80),
    editora varchar(80),
    isbn varchar(50),
    titulo varchar(80),
    CONSTRAINT livros_pkey PRIMARY KEY (id)
    );


CREATE TABLE IF NOT EXISTS usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email varchar(80),
    endereco varchar(255),
    nome varchar(80),
    senha varchar(80),
    telefone varchar(20),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
    );

CREATE TABLE emprestimo (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    usuario_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,
    data_emprestimo DATE NOT NULL,
    data_devolucao_prevista DATE NOT NULL,
    data_devolucao_real DATE,
    devolvido BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_emprestimo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_emprestimo_livro FOREIGN KEY (livro_id) REFERENCES livro(id)
);
